### ISSUE TITLE
FreeWEID does not work

### ISSUE THREAD

**Issue by danielmarschall** [frdl/frdl-oidplus-plugin-page-frdlweb-freeoid#1]
Hello.

At this line https://github.com/frdl/frdl-oidplus-plugin-page-frdlweb-freeoid/blob/017f6945a0ac9ecb51e4fcbc730ee92aa5632741/plugins/publicPages/200_frdlweb_freeoid/manifest.xml#L22 , the "script.js" should be replaced by "OIDplusPagePublicFreeOIDFrdlweb.js".

I hope that I could help you with this bug report.
Thank you for developing OIDplus plugins!

Take care,
Daniel Marschall

**Comment by wehowski** [comment]
Hello Daniel,
fxed in v0.0.4
Thank you! 

Thank you for OIDPlus and your great support!
Till
