### ISSUE TITLE
FreeWEID: Whois query outputs warning

### ISSUE THREAD

**Issue by danielmarschall** [frdl/frdl-oidplus-plugin-page-frdlweb-freeoid#2]
Hello,

When I call

https://registry.frdl.de/plugins/publicPages/100_whois/whois/webwhois.php?format=txt&query=oid%3A1.3.6.1.4.1

I am getting a warning.

At line 24 and line 27, oidObject is used, which is not existing.

**Comment by wehowski** [comment]
Hello Daniel,
fixed in v0.0.5

Thank you very much!
Till
