### ISSUE TITLE
Deprecated functions getSystemUrl()

### ISSUE THREAD

**Issue by danielmarschall** [frdl/frdl-oidplus-plugin-page-frdlweb-freeoid#3]
Hi,

I wanted to inform you that with the new version of OIDplus, the functions OIDplus::getSystemUrl() and OIDplus::basePath() have been removed in order to make the API a bit easier to understand. Their functionalities have been moved into the functions OIDplus::webpath() and OIDplus::localpath().
A small overview is placed in doc/developer_notes/

Please change:

OIDplus::getSystemUrl() to OIDplus::webpath()
OIDplus::getSystemUrl(true) to OIDplus::webpath(null,true)
OIDplus::getSystemUrl(false) to OIDplus::webpath(null,false)

OIDplus::basePath() to OIDplus::localpath()

Thank you very much and sorry for the inconveniences.

Kind regards,
Daniel Marschall

PS: These functions shall always return a trailing path delimiter ( / ) on directories.

**Comment by wehowski** [comment]
# fixed version v0.0.5.3
Thank you Daniel!
---
If the bug is not fixed, pleased open a new issue.
---

mfg
Till
